# This file was generated by GoReleaser. DO NOT EDIT.
cask "knit" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "9ecc5723368a8bf21746f9037ddab9b90d2a8129270cbd9e0839ba5b875eaa50"
      url "https://github.com/oddurs/knit/releases/download/v#{version}/knit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b41a9682fdd4ca45eb0dd6f349e21cab60a930a3730917020d9ac1d57ca344b5"
      url "https://github.com/oddurs/knit/releases/download/v#{version}/knit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7a227a29f3fc124c12917a6d2ca4b0e20e165f28e03ef26037812e919e9b588a"
      url "https://github.com/oddurs/knit/releases/download/v#{version}/knit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8f9397578b5c3b614d1ab3c94c6b3fc01ac331186d7b07c89e8dc28064dcc1e7"
      url "https://github.com/oddurs/knit/releases/download/v#{version}/knit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "knit"
  desc "Weave your machines into one fabric. Zero-config compute sharing."
  homepage "https://github.com/oddurs/knit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "knit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/knit"]
    end
  end

  # No zap stanza required
end
