# This file was generated by GoReleaser. DO NOT EDIT.
cask "knit" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "ae7bc8e37514f0c640e71c956a5ecbe41bed804f2991140e5e9e711dda4d4815"
      url "https://github.com/oddurs/knit/releases/download/v#{version}/knit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "973a5d52688cae4db876690587a31283e2666414b09c27877607ff084b7c97a6"
      url "https://github.com/oddurs/knit/releases/download/v#{version}/knit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d130db683f582d288c7c8474c65329b76547713fd483337dfa1e126c2fd86368"
      url "https://github.com/oddurs/knit/releases/download/v#{version}/knit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c3bfd3faf805a53e714b3f579103d90cd385b6d98f54bbd38b202a53bbf6b812"
      url "https://github.com/oddurs/knit/releases/download/v#{version}/knit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "knit"
  desc "Weave your machines into one fabric. Zero-config compute sharing."
  homepage "https://github.com/oddurs/knit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "knit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/knit"]
    end
  end

  # No zap stanza required
end
