# This file was generated by GoReleaser. DO NOT EDIT.
cask "knit" do
  version "0.4.1"

  on_macos do
    on_arm do
      sha256 "0d604fdcfd20ec0ce720efe9a19783437d770cdeb8af593d2f350ed69aa09df4"
      url "https://github.com/oddurs/knit/releases/download/v#{version}/knit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "08acefbd53f34052dd85580e66e313d7f715c62ad30909cf4c7d66bf6b6f2e3a"
      url "https://github.com/oddurs/knit/releases/download/v#{version}/knit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "383112c51e7427a54fe4c9fac3d784c0255b39598efff0be85c0fb148c60fac7"
      url "https://github.com/oddurs/knit/releases/download/v#{version}/knit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e137a6df4474b0b723f7a0b46e115829903108184c94a1545fea3c7781355e32"
      url "https://github.com/oddurs/knit/releases/download/v#{version}/knit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "knit"
  desc "Weave your machines into one fabric. Zero-config compute sharing."
  homepage "https://github.com/oddurs/knit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "knit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/knit"]
    end
  end

  # No zap stanza required
end
