# Generated by scripts/formula from the release's SHA256SUMS. Do not edit by
# hand: the next release overwrites it.
class Harrow < Formula
  desc "Work a cairn backlog from the terminal"
  homepage "https://github.com/oddurs/harrow"
  version "0.2.0-alpha.1"
  license "MIT"

  # harrow reads a cairn backlog without it and changes one with it. The line
  # harrow is paired with: while that is a pre-release, the tap carries it as
  # cairn-next, and plain cairn is the stable release before it.
  depends_on "oddurs/cairn/cairn-next" => :optional

  on_macos do
    on_arm do
      url "https://github.com/oddurs/harrow/releases/download/v#{version}/harrow-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "0dea781f43e103771261961917b71ca39044d7295a9f076446ea22a335409b7d"
    end
    on_intel do
      url "https://github.com/oddurs/harrow/releases/download/v#{version}/harrow-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "6a34e475cca30d89e4a4e3fec143c98c04f0e2148e2855c05b5d219049397bf2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/oddurs/harrow/releases/download/v#{version}/harrow-#{version}-aarch64-unknown-linux-musl.tar.gz"
      sha256 "a33cf405716daa0f03e63f7ff9ecb847d09c053646df973582e1f5c3b19e1876"
    end
    on_intel do
      url "https://github.com/oddurs/harrow/releases/download/v#{version}/harrow-#{version}-x86_64-unknown-linux-musl.tar.gz"
      sha256 "29f1c8372f8a5d7144f8709717fcda1160a1039439e7e06add814d5a02360e9b"
    end
  end

  def install
    bin.install "harrow"
    doc.install "README.md", "THEMES.md"

    # Generated by the binary being installed rather than shipped beside it,
    # so they cannot describe a different version from the one on PATH.
    (man1/"harrow.1").write Utils.safe_popen_read(bin/"harrow", "man")
    # Homebrew appends the shell's name, which is how harrow takes it:
    # `harrow completions fish`.
    generate_completions_from_executable(bin/"harrow", "completions")
  end

  test do
    assert_match "harrow #{version}", shell_output("#{bin}/harrow --version")
    assert_match "work a cairn backlog", shell_output("#{bin}/harrow man")
    assert_path_exists man1/"harrow.1"
  end
end
